services:
  ##############
  # Networking #
  ##############
  tor.sov:
    build:
      context: ./tor
      args:
        - BUILD_NUM_PROCS=${BUILD_NUM_PROCS}
    container_name: tor.sov
    restart: unless-stopped
    ports:
      - 9050:9050
      - 9051:9051
    volumes:
      - /data/tor:/tor
    networks:
      - internal-sov

  tailscale.sov:
    image: tailscale/tailscale:stable
    pull_policy: always
    container_name: tailscale.sov
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /tmp:/tmp
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_EXTRA_ARGS=--advertise-exit-node --hostname=${TAILSCALE_HOSTNAME}
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW

  caddy.sov:
    image: caddy:latest
    pull_policy: always
    container_name: caddy.sov
    restart: unless-stopped
    volumes:
      - /data/caddy/data:/data
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /tmp/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    ports:
      - 80:80
      - 443:443
    networks:
      - internal-sov

  ##############
  # Monitoring #
  ##############
  cadvisor.sov:
    image: ${CADVISOR_IMAGE}:v0.47.1
    container_name: cadvisor.sov
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 13001:8080
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true

  bitcoind-exporter.sov:
    image: jvstein/bitcoin-prometheus-exporter:latest
    container_name: bitcoind-exporter.sov
    restart: unless-stopped
    environment:
      - BITCOIN_RPC_HOST=bitcoind.sov
      - BITCOIN_RPC_USER=${BITCOIND_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIND_RPC_PASSWORD}
      - REFRESH_SECONDS=1
      - LOG_LEVEL=INFO
    ports:
      - 9332:9332
    depends_on:
      - bitcoind.sov
    networks:
      - internal-sov

  ###########
  # Bitcoin #
  ###########
  bitcoind.sov:
    build:
      context: ./bitcoind
      args:
        - BUILD_NUM_PROCS=${BUILD_NUM_PROCS}
    container_name: bitcoind.sov
    restart: unless-stopped
    stop_grace_period: 5m
    ports:
      - 8333:8333
    volumes:
      - /data/bitcoind/data:/data
    networks:
      - internal-sov

  electrs.sov:
    build:
      context: ./electrs
      args:
        - BUILD_NUM_PROCS=${BUILD_NUM_PROCS}
    container_name: electrs.sov
    restart: unless-stopped
    stop_grace_period: 5m
    ports:
      - 50001:50001
      - 4224:4224 # metrics
    volumes:
      - /data/electrs/data:/data
      - /data/electrs/conf:/etc/electrs
    networks:
      - internal-sov

  jam.sov:
    image: ghcr.io/joinmarket-webui/jam-standalone # TODO: freeze version
    container_name: jam.sov
    restart: unless-stopped
    environment:
      - JM_RPC_HOST=bitcoind.sov
      - JM_RPC_PORT=8332
      - JM_RPC_USER=${BITCOIND_RPC_USER}
      - JM_RPC_PASSWORD=${BITCOIND_RPC_PASSWORD}
      - JM_ENSURE_WALLET=true
    ports:
      - 3580:80
    volumes:
      - /data/jam/data:/root/.joinmarket
    networks:
      - internal-sov

  #############
  # Lightning #
  #############
  lnd.sov:
    build:
      context: ./lnd
      args:
        - BUILD_NUM_PROCS=${BUILD_NUM_PROCS}
    container_name: lnd.sov
    restart: unless-stopped
    stop_grace_period: 5m
    ports:
      - 9735:9735 # P2P
      - 28080:8080 # REST
    volumes:
      - /data/lnd/data:/root/.lnd
      - /data/tor:/tor
    networks:
      - internal-sov

  rtl.sov:
    image: shahanafarooqui/rtl:0.15.1
    container_name: rtl.sov
    restart: unless-stopped
    volumes:
      - /data/lnd/data:/root/.lnd:ro
      - /data/rtl/data:/database
      - /data/rtl/conf:/config
    ports:
      - 8585:8585
    environment:
      RTL_CONFIG_PATH: /config
      RTL_SSO: 0
    networks:
      - internal-sov

  thunderhub.sov:
    image: apotdevin/thunderhub:v0.13.31
    container_name: thunderhub.sov
    restart: unless-stopped
    environment:
      - ACCOUNT_CONFIG_PATH=/data/thubConfig.yaml
      - MEMPOOL_URL=${THUNDERHUB_MEMPOOL_URL}
    volumes:
      - /data/lnd/data:/lnd:ro
      - /data/thunderhub/data:/data
    ports:
      - 8686:3000
    networks:
      - internal-sov

  #################
  # Miscellaneous #
  #################
  syncthing.sov:
    image: syncthing/syncthing
    container_name: syncthing.sov
    hostname: ${SYNCTHING_HOSTNAME}
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/syncthing:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    network_mode: host

  vaultwarden.sov:
    image: vaultwarden/server:latest
    pull_policy: always
    container_name: vaultwarden.sov
    restart: unless-stopped
    volumes:
      - /data/vaultwarden/data:/data
    networks:
      - internal-sov

networks:
  internal-sov:
    # Internal network, all services should belong in it,
    # so that they can communicate with each other.
