version: "3.9"

services:
  ##############
  # Networking #
  ##############
  tor.sov:
    build: ./tor
    container_name: tor.sov
    restart: unless-stopped
    ports:
      - 9050:9050
      - 9051:9051
    volumes:
      - /data/tor:/tor
    networks:
      - internal-sov

  tailscale.sov:
    image: tailscale/tailscale
    container_name: tailscale.sov
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_EXTRA_ARGS=--advertise-exit-node --hostname=${TAILSCALE_HOSTNAME}
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW

  ##############
  # Monitoring #
  ##############
  cadvisor.sov:
    image: ${CADVISOR_IMAGE}:v0.47.1
    container_name: cadvisor.sov
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 13001:8080
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true

  ###########
  # Bitcoin #
  ###########
  bitcoind.sov:
    build: ./bitcoind
    container_name: bitcoind.sov
    restart: unless-stopped
    stop_grace_period: 5m
    ports:
      - 8333:8333
    volumes:
      - /data/bitcoind/data:/data
    networks:
      - internal-sov

  electrs.sov:
    build: ./electrs
    container_name: electrs.sov
    restart: unless-stopped
    stop_grace_period: 5m
    ports:
      - 50001:50001
    volumes:
      - /data/bitcoind/data:/bitcoin:ro
      - /data/electrs/data:/data
    environment:
      - ELECTRS_LOG_FILTERS=INFO
      - ELECTRS_DAEMON_DIR=/bitcoin
      - ELECTRS_DB_DIR=/data
      - ELECTRS_DAEMON_P2P_ADDR=bitcoind.sov:8333
      - ELECTRS_DAEMON_RPC_ADDR=bitcoind.sov:8332
      - ELECTRS_ELECTRUM_RPC_ADDR=0.0.0.0:50001
    networks:
      - internal-sov

networks:
  internal-sov:
    # Internal network, all services should belong in it,
    # so that they can communicate with each other.
